# .github/workflows/ai-review.yml
name: Gemini AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: # allows manual runs from Actions tab

jobs:
  ai-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run Gemini AI review
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          # GITHUB_REPOSITORY is automatically provided by GitHub
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          npx ts-node src/ci-review.ts
